### ISSUE TITLE
install intel-parallel-studio does not (fully) respect ~tbb ~mkl

### ISSUE THREAD

**Issue by tz-rrze** [spack/spack#11144]
**spack install intel-parallel-studio does not (fully) respect ~tbb ~mkl, i.e. TBB is still installed and TBBROOT as well as I_MPI_ROOT, FI_PROVIDER are set. TBB is also included in CPATH, LD_LIBRARY_PATH and LIBRARY_PATH**

### Steps to reproduce the issue

```console
$ spack install intel-parallel-studio@composer.2019.3  % intel@19.0.3 ~tbb ~mpi ~mkl ~ipp ~daal
...
/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6
$ spack find -v -f  /ity7pi3oqm
==> 1 installed package
-- linux-centos7-x86_64 / intel@19.0.3 --------------------------
intel-parallel-studio@composer.2019.3%intel~advisor~clck~daal~gdb~ilp64~inspector~ipp~itac~mkl~mpi~newdtags+rpath+shared~tbb threads=none ~vtune
$ module show intel-paralle-studio/composer.2019.3-intel19.0.3-ity7pi3
...
prepend-path    CPATH   /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/pstl/include:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/include:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/include
prepend-path    LD_LIBRARY_PATH /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/release:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7
prepend-path    LIBRARY_PATH    /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7
setenv          TBBROOT /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/tbb
...
prepend-path    CLASSPATH       /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/mpi.jar:/apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/lib/mpi.jar
prepend-path    FI_PROVIDER_PATH        /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib/prov
setenv          I_MPI_ROOT      /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi
prepend-path    MANPATH /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/man
prepend-path    MANPATH /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/man
prepend-path    PATH    /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/bin
prepend-path    PATH    /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/bin
prepend-path    PATH    /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/bin
prepend-path    PATH    /apps/SPACK-Stage1/opt/linux-centos7-x86_64/intel-19.0.3/intel-parallel-studio-composer.2019.3-ity7pi3oqmqzjpguwiho3lm7i7vfuiu6/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/bin
```

(I'm not sure why all MPI lines appear twice in the module file ... - they are actually there twice; it's not a copy&paste error)

### Expected behavior

TBB should not appear at all in the module file (and also should not be on the file system - but $TBBROOT contains the full TBB installation as with +tbb)

For MPI it might be less obvious as even the Composer edition comes with the MPI runtime. However, when you want to combine the Intel compilers with other MPIs and use the SPACK provided modules outside of SPACK, the current situation causes trouble as the selected mpirun/mpiexec depends on the order modules are loaded.

### Information on your system

* CentOS 7.6
* SPACK is currently used in a chain configuration with the chain using a checkout from April 8th (db98f16) while the upstream is much older (but that hopefully should be irrelevant as there are no relevant packages in the upstream)

**Comment by g-mathias** [comment]
I see the same issue.  I've checked the installation logs of intel-parallel-studio and found that intel-ifort has a dependency on intel-mpi; probably because of coarrays. This is automatically resolved by the intel installer

```
> grep intel-mpi-rt__x86_64 cluster.2019.4-gcc-hdt5emi/.spack/intel.pset.*06.24.23.17.07.2019.log
23:17:07:477 : setComponentSelection: failed dependence for 'intel-ifort__x86_64' to 'intel-mpi-rt__x86_64' (2) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:07:477 : setComponentSelection: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:07:477 : setComponentSelection: change 'intel-mpi-rt__x86_64' state from selected '0' to '1' 
23:17:07:477 : setComponentSelection: failed dependence for 'intel-mpi-rt__x86_64' to 'intel-mpi-doc__x86_64' (4) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:07:477 : setComponentSelection: failed dependence for 'intel-mpi-rt__x86_64' to 'intel-conda-impi_rt-linux-64-shadow-package__x86_64' (7) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:07:480 : fixDependencies: enabling component: intel-mpi-rt__x86_64
23:17:07:480 : selectUnselectComponent: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:07:480 : setComponentSelection: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:07:480 : setComponentSelection: change 'intel-mpi-rt__x86_64' state from selected '0' to '1' 
23:17:09:121 : setComponentSelection: failed dependence for 'intel-ifort__x86_64' to 'intel-mpi-rt__x86_64' (2) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:09:121 : setComponentSelection: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:09:121 : setComponentSelection: change 'intel-mpi-rt__x86_64' state from selected '0' to '1' 
23:17:09:121 : setComponentSelection: failed dependence for 'intel-mpi-rt__x86_64' to 'intel-mpi-doc__x86_64' (4) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:09:121 : setComponentSelection: failed dependence for 'intel-mpi-rt__x86_64' to 'intel-conda-impi_rt-linux-64-shadow-package__x86_64' (7) of product 'Intel MPI Library 2019 Update 4' (16)
23:17:09:125 : fixDependencies: enabling component: intel-mpi-rt__x86_64
23:17:09:125 : selectUnselectComponent: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:09:125 : setComponentSelection: product Intel MPI Library 2019 Update 4, component: intel-mpi-rt__x86_64
23:17:09:125 : setComponentSelection: change 'intel-mpi-rt__x86_64' state from selected '0' to '1' 
```
So either the IntelPackage needs a ~ifort variant, or somebody has to persuade Intel to implement a 'disable dependency resolution' option.

**Comment by alalazo** [comment]
This issue is very likely still present, but it's more with the Intel recipe than a bug in core Spack. Removed the label.

**Comment by alalazo** [comment]
Closing, as this issue seems outdated.
