### ISSUE TITLE
Fenics build fails with missing ufc.h

### ISSUE THREAD

**Issue by rkalescky** [spack/spack#5693]
Hi all, I've been trying to build Fenics using:

`spack install fenics%gcc@6.3.0+petsc+parmetis+mpi+slepc+trilinos ^mvapich2%gcc@6.3.0 fabrics=sock process_managers=slurm threads=multiple ^petsc@3.7.6%gcc@6.3.0+boost~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared+superlu-dist~trilinos ^metis%gcc@6.3.0+real64 ^slepc%gcc@6.3.0~arpack`

This builds everything, but then fails during Fenics with many instances of:

`fatal error: ufc.h: No such file or directory`

I've attached log file and any help is greatly appreciated.

[spack-build.log](https://github.com/LLNL/spack/files/1376262/spack-build.log)

**Comment by davydden** [comment]
judging from 
```
In file included from /hpc/spack/var/spack/stage/fenics-2016.1.0-5534rwnsxjeo2c6gpxdm3xs7episeulv/dolfin-2016.1.0/dolfin/adaptivity/ErrorControl.cpp:37:0:
/hpc/spack/var/spack/stage/fenics-2016.1.0-5534rwnsxjeo2c6gpxdm3xs7episeulv/dolfin-2016.1.0/dolfin/fem/UFC.h:28:17: fatal error: ufc.h: No such file or directory
 #include <ufc.h>
                 ^
```
it looks like a bug in `fenics`. I would try submitting upstream. They probably have a mailing list or github or Google groups to report issues...

**Comment by scheibelp** [comment]
That build log contains an error message earlier:

> UFC could not be found. (missing: UFC_INCLUDE_DIRS UFC_VERSION UFC_VERSION_OK UFC_SIGNATURE) (Required is at least version "2016.1")

Which leads to https://fenicsproject.org/qa/8840/question-about-installation-from-source-code

Maybe `UFC_DIR` has to be set? `ufc.h` is apparently part of `ffc` which is also provided by fenics (and built by this package?)

**Comment by rkalescky** [comment]
Yes, thank you. Several other post referenced `UFC_DIR` as well. What is the best way to set this variable during the compilation? I have tried
```
    def setup_environment(self, spack_env, run_env):
        spack_env.set('UFC_DIR', join_path(self.stage.source_path, 'depends', 'ffc'))
```
just after the `cmake_args`. This gives the same error during the build, but I'm not sure if its due to variable not actually being set or if Fenics is just ignoring it.

**Comment by scheibelp** [comment]
> just after the cmake_args

FWIW the order of definitions shouldn't matter

> What is the best way to set this variable during the compilation?

Defining `setup_environment` as you did is the way to do it.

> I'm not sure if its due to variable not actually being set or if Fenics is just ignoring it.

The stage directory will contain a `spack-build.env` file that should mention all the environment variables that are set (and `UFC_DIR` should be included along with them).

As a sanity check, are you certain that `UFC_DIR` is what it should be?

**Comment by ch741** [comment]
I think the issue is that the `build_python_components` and `install_python_components` functions run after the build and install phases. They should both run before the cmake phase so changing to the following should fix that:

```
    @run_before('cmake')
    def build_python_components(self):
        for package in self.python_components:
            with working_dir(join_path('depends', package)):
                setup_py('build')


    @run_before('cmake')
    def install_python_components(self):
        for package in self.python_components:
            with working_dir(join_path('depends', package)):
                setup_py('install', '--prefix={0}'.format(self.prefix))
```

**Comment by thelfer** [comment]
Dear all,
I run into a similar issue with spack/master (see below). The solution proposed by @ch741 does not work.
Regards

~~~~
$ spack install fenics^hdf5+fortran

==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

34 errors found in build log:
     1595    make -f dolfin/swig/modules/mesh/CMakeFiles/mesh_swig_compilation.dir/build.make dolfin/swig/modules/mesh/CMakeFiles/mesh_swig_compilation.dir/build
     1596    make[2]: Entering directory '/tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build'
     1597    [  1%] Swig compile module.i for python
     1598    cd /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh && /home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-deb
             ian9-x86_64/gcc-6.3.0/cmake-3.13.1-q5pueu2c4ydzn2zpw2pctq6oiatcr32o/bin/cmake -E make_directory /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/
             swig/modules/mesh /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh
     1599    cd /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh && /home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-deb
             ian9-x86_64/gcc-6.3.0/cmake-3.13.1-q5pueu2c4ydzn2zpw2pctq6oiatcr32o/bin/cmake -E touch /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modu
             les/mesh/CMakeFiles/_mesh.dir/modulePYTHON.stamp
     1600    cd /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh && /home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-deb
             ian9-x86_64/gcc-6.3.0/cmake-3.13.1-q5pueu2c4ydzn2zpw2pctq6oiatcr32o/bin/cmake -E env SWIG_LIB=/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_6
             4/gcc-6.3.0/swig-3.0.12-dwyjxipjqwcynuedv66h662y46r6iytt/share/swig/3.0.12 /home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/swig-3.
             0.12-dwyjxipjqwcynuedv66h662y46r6iytt/bin/swig3.0 -python -module mesh -shadow -modern -modernargs -fastdispatch -fvirtual -nosafecstrings -noproxydel -fastproxy -fastinit -fas
             tunpack -fastquery -nobuildnone -Iinclude/swig -DNDEBUG -DDOLFIN_SIZE_T=8 -DDOLFIN_LA_INDEX_SIZE=4 -DHAS_HDF5 -DHAS_TRILINOS -DHAS_SLEPC -DHAS_PETSC -DHAS_UMFPACK -DHAS_CHOLMOD
              -DHAS_SCOTCH -DHAS_PARMETIS -DHAS_ZLIB -DHAS_MPI -DHAS_OPENMP -DNUMPY_VERSION_MAJOR=1 -DNUMPY_VERSION_MINOR=15 -DNUMPY_VERSION_MICRO=2 -DNPY_NO_DEPRECATED_API=NPY_1_15_API_VER
             SION -outdir /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh -c++ -I/tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1
             .0/spack-build -I/home/th202608/codes/spack/official/master/src/spack/var/spack/stage/fenics-2016.1.0-ylwltdg4cigzxnl3cuuc6b4fxvwtn27l/dolfin-2016.1.0 -I/home/th202608/codes/sp
             ack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/slepc-3.10.1-hwdrdc62fxigj2ml45o76toc7fwjvycc/include -I/home/th202608/codes/spack/official/master/src/sp
             ack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/suite-sparse-5.3.0-xd4moigqqgtoqzhs3xw53wk3lal2ayr6/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-
             debian9-x86_64/gcc-6.3.0/scotch-6.0.6-gktipnpf6tfk77we73ibsueqcr7w7zgy/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/z
             lib-1.2.11-lgevn3ckxbm4sxwjdoq3k5qfgmpsjt7o/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/openmpi-3.1.3-2klqcu7yivgz6c
             paf5l2idb26lx2agzz/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/eigen-3.3.5-ch7xuir4zkwxfxqfsldfrhuxmag4e6nr/include/
             eigen3 -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/boost-1.68.0-2wulxhw3khv4tstcpbocd32ngmn6bmd7/include -I/home/th202608/co
             des/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/hdf5-1.10.4-ryycdhfq5vehlbivaz7c3sljyddqu7if/include -I/home/th202608/codes/spack/official/master/s
             rc/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/trilinos-12.12.1-hndyp4s7iqcw6bh4liy74itapj3lecvx/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/lin
             ux-debian9-x86_64/gcc-6.3.0/petsc-3.10.2-kz6m6c35eoxlonu3rgfsmkzqx5wkeg7m/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.
             0/superlu-dist-5.4.0-fn2sr4s3bfblqwfsqmlhsjiekvimz7tr/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/hypre-2.15.1-ni7do
             akzlpn43g6baxyy7ucywpqdjsdd/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/parmetis-4.0.3-jm66rp6umpwfds43sbh5megjx5y3u
             i2f/include -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/metis-5.1.0-jj2hpmf3df6v37rsc77lec26ep7ac5bj/include -I/home/th20260
             8/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-numpy-1.15.2-btjnzmvgjwtwvte42ddncmbnv2jvxrxo/lib/python2.7/site-packages/numpy/core/include
              -I/home/th202608/codes/spack/official/master/src/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/python-2.7.15-axcadqam4b5rylenqflfxztsaaidiny2/include/python2.7 -o /tmp/th2026
             08/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/modules/mesh/modulePYTHON_wrap.cxx /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-
             build/dolfin/swig/modules/mesh/module.i
  >> 1601    /tmp/th202608/spack-stage/spack-stage-MZEKko/dolfin-2016.1.0/spack-build/dolfin/swig/common/pre.i:103: Error: Unable to find 'ufc.h'
~~~~

[spack-build.out.txt](https://github.com/spack/spack/files/2673506/spack-build.out.txt)

**Comment by jthies** [comment]
the issue still seems to persist in the current spack/develop branch

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if the problem persists.
