### ISSUE TITLE
nginx-1.12.0 fails with gcc-7.1.0

### ISSUE THREAD

**Issue by stefanosoffia** [spack/spack#6252]
The command `spack install nginx` fails with the compile errors below.
AFAIK these errors are due to the `-Werror` flag paired with the fairly recent `gcc@7.1.0`.

```
4 errors found in build log:
     [ ... ]
     226        -o objs/src/core/ngx_resolver.o \
     227        src/core/ngx_resolver.c
     228   /home/gip/spack_local/lib/spack/env/gcc/gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs
 \
     229        -o objs/src/core/ngx_open_file_cache.o \
     230        src/core/ngx_open_file_cache.c
     231   src/core/ngx_murmurhash.c: In function ‘ngx_murmur_hash2’:
  >> 232   src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
     233            h ^= data[2] << 16;
     234            ~~^~~~~~~~~~~~~~~~
     235   src/core/ngx_murmurhash.c:38:5: note: here
     236        case 2:
     237        ^~~~
  >> 238   src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
     239            h ^= data[1] << 8;
     240            ~~^~~~~~~~~~~~~~~
     241   src/core/ngx_murmurhash.c:40:5: note: here
     242        case 1:
     243        ^~~~
     244   cc1: all warnings being treated as errors
     245   objs/Makefile:470: recipe for target 'objs/src/core/ngx_murmurhash.o' failed
  >> 246   make[1]: *** [objs/src/core/ngx_murmurhash.o] Error 1
     247   make[1]: *** Waiting for unfinished jobs....
```

**Comment by adamjstewart** [comment]
We could filter out the `-Werror` flag from the Makefile if you want. Or do you not care now that #6810 has been merged? Feel free to close this if so.

**Comment by stefanosoffia** [comment]
I'm more than happy to just go with nginx v1.13.8 now that it merged. Moreover, AFAIK `-Werror` comes directly from nginx authors, therefore I see some value keeping it.

**Comment by adamjstewart** [comment]
> But since you mentioned also the _Makefile patching_ option, what is the Spack suggested best practice for this cases?

It depends on how much of a hero you want to be. Ideally, every version of every package in Spack will build with every version of every compiler. Of course, this will never be the case, but any work done in that direction is always noble work.

Quite often I will see packages that are only designed to build with GCC, and will hardcode GCC-specific flags. When I need to build something with PGI I will have to overwrite these flags with the PGI equivalents or just remove them altogether.

If you check out the `jemalloc` package, you'll actually see an example where we run `configure` and then remove `-Werror` from the Makefile.

**Comment by mashirozx** [comment]
@stefanosoffia Have you solved this problem? Met the same problem compiling Nginx module, so may be not spack's problem but Nginx it self?

**Comment by adamjstewart** [comment]
@stefanosoffia's problem was solved by #6810. Are you building the latest version of `nginx`, or are you using a different compiler? Like I said, it shouldn't be hard to filter out these compiler flags if we need to.

**Comment by mashirozx** [comment]
@adamjstewart Thank you! No problem now. I used to compile with Nginx -1.12.1 (Ubuntu), which is the latest release on <https://launchpad.net/ubuntu>, but nowI've manually compile & upgraded to v1.12.2~ XD

**Comment by adamjstewart** [comment]
Ah, I see. Yes, I believe this was an `nginx` bug. It was fixed in 1.13.8, possibly in older versions as well.

**Comment by RichardTMiles** [comment]
Looks like this error is back in version 1.2.1 
Running Amazon Linux 2 on EC2
